version: "3.8"

services:
# БД
  db_pgsql:
    container_name: db_pgsql_box
    build:
      context: ./postgresql
    restart: always
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
    expose:
      - "5432"
    volumes:
      - ./pgsql_data:/var/lib/postgresql/data
    networks:
      dev:
        ipv4_address: 192.168.60.11
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.60.0/24
